#11 setup of required data
Sybit-Education/COVID-Bouncer-Admin pull request #29
Opened 2020-12-14 09:22 UTC by mirko-pleli

2020-12-14 09:26 UTC, closed without merging

2020-12-14 10:06 UTC, chrisWolter requested changes

2020-12-14 10:06 UTC, chrisWolter commented on src/router/index.js
> +import Location from '../views/setup/Location'
Please change name to a more suitable

2020-12-14 10:06 UTC, chrisWolter commented on src/router/index.js
> +import Building from '@/views/setup/Building'
please change name to a more suitable

2020-12-14 10:06 UTC, chrisWolter commented on src/router/index.js
> +    name: 'MasterPassword',
Please dont change home variable to Masterpassword. With this change it will open the masterpassword page everytime  the app is opened. You have to make a guard for this.

You could add a new route (/setup/masterpassword)

2020-12-14 10:06 UTC, chrisWolter commented on src/services/config.service.js
> +        return false
do not return a boolean, instead, throw an exception.

2020-12-14 10:06 UTC, chrisWolter commented on src/services/config.service.js
> +      .then(function () {
remove this block

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Building.vue
> +        <h3 class="text-center pb-3">Setup from the COVID-Bouncer Admin</h3>
Typo: Setup for the COVID-Bouncer

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Building.vue
> +  <b-row class="mt-3 align-content-center">
Change to b-container

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Building.vue
> +    <b-col class="building">
This col is obsolet

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Building.vue
> +      <b-col>
Change to b-row

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Building.vue
> +      <form>
Please wrap in a row. The Headline should be a single row and the Table should be a new Row. This helps to wrap the whole page.

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Building.vue
> +        <b-col>
This is also an row

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Building.vue
> +      const response = await locationService.addBuilding(this.building, this.location)
Please use a try catch here and throw an exception instead of returning a boolean

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Building.vue
> +      building: undefined
do not set a initial value to undefined. This could lead to problems

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Location.vue
> +        <h3 class="text-center pb-3">Setup from the COVID-Bouncer Admin</h3>
Typo

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Location.vue
> +  <b-row class="mt-3 align-content-center">
Use b-container

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Location.vue
> +    <b-col class="location">
This col is obsolet

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Location.vue
> +      <b-col>
This is a b-row

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Location.vue
> +      <form>
please wrap with a row

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Location.vue
> +        <b-col>
This is a b-row

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Location.vue
> +              min="5"
Why cant a location have less than 5 digits?

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Building.vue
> +              min="5"
Why cant a building have less than 5 digits?

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/Location.vue
> +      const response = await locationService.setLocation(this.location)
Please use a try catch here and return an exception instead of an boolean

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/MasterPassword.vue
> +      <h3 class="text-center pb-3">Welcome to the Setup from the COVID-Bouncer Admin</h3>
Typo: of the Covid-Bouncer

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/MasterPassword.vue
> +<b-row class="mt-3 align-content-center">
this is a b-container

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/MasterPassword.vue
> +  <b-col class="masterPassword">
This col is obsolet

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/MasterPassword.vue
> +    <b-col>
This is a row

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/MasterPassword.vue
> +    <form>
Wrap with a row

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/MasterPassword.vue
> +      <b-col>
this is a row

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/MasterPassword.vue
> +        masterPassword: undefined
dont set a init value to undefined

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/MasterPassword.vue
> +      config: {
dont wrap this. 
```suggestion
      masterpassword: ''
```

2020-12-14 10:06 UTC, chrisWolter commented on src/views/setup/MasterPassword.vue
> +      const response = await configService.setMasterPassword(this.config.masterPassword)
use a try catch here and throw an exception if something went wrong instead of returning a boolean

2020-12-14 10:09 UTC, chrisWolter commented
- [ ] It is not possible to add multiple locations/buildings

- [ ] the router to the dashboard doesnt work.

2020-12-16 13:18 UTC, mirko-pleli commented
Done